version: '3.8'

services:
  mysql:
    image: mysql:8.0.42
    container_name: flyway-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flyway-net

volumes:
  mysql_data:

networks:
  flyway-net:
