spring:
  application:
    name: authentication
  datasource:
    # url: jdbc:mysql://localhost:3311/authentication_db
    # username: root
    # password: root
    url: jdbc:mysql://db-test2.cjkocssqm352.eu-central-1.rds.amazonaws.com:3306/sampledb
    username: admin
    password: Linhhiep273
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    cleanDisabled: false
  docker:
    compose:
      enabled: false
server:
  port: 8085
logging:
  level:
    org:
      springframework: INFO
      hibernate:
            SQL: INFO
      flywaydb: ERROR   
jwt:
  secret: your_secret_key_here_need_to_have_more_than_32_characters
  expirationTime: 3600000

